In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('Box_Office.csv')
df.head(10)

In [ ]:
x=df[['Days','Bahu_collections']]
y=df[['Days','Dangal_collections']]

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
feature = df.iloc[:, 0:1].values
label_bahubali = df.iloc[:, 1:2].values   # Bahubali 2
label_dangal = df.iloc[:, 2:3].values 
feature,label_bahubali,label_dangal

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]], dtype=int64),
 array([[41.  ],
        [40.5 ],
        [46.5 ],
        [40.25],
        [30.  ],
        [26.  ],
        [22.75],
        [19.75],
        [26.5 ]]),
 array([[29.78],
        [34.82],
        [42.35],
        [25.48],
        [23.07],
        [21.2 ],
        [20.29],
        [17.  ],
        [31.27]]))

In [18]:
clf1=LinearRegression()
clf1.fit(feature, label_bahubali)
clf2=LinearRegression()
clf2.fit(feature, label_dangal)
clf1,clf2

(LinearRegression(), LinearRegression())

In [23]:
bahubali_collection = clf1.predict([[10]])


dangal_collection = clf2.predict([[10]])

In [26]:
bahubali_collection #day 10 Erning

array([[17.41666667]])

In [27]:
dangal_collection #day 10 Erning

array([[19.25944444]])